import type { ConstantSource } from './provenance';

export interface ExtractionPreset {
  id: string;
  label: string;
  formula: string;
  type: 'acid' | 'chelate';
  logKd: number;
  pKas: number[];
  neutralIdx: number;
  system: string;
  source: ConstantSource;
  n?: number;
  logCHL?: number;
}

export const EXTRACTION_PRESETS: ExtractionPreset[] = [
  {
    id: 'benzoico',
    label: 'Ácido benzoico',
    formula: 'C₆H₅COOH',
    type: 'acid',
    logKd: 2.22,
    pKas: [4.20],
    neutralIdx: 0,
    system: 'CHCl₃/H₂O',
    source: {
      citation: 'Harris, Quantitative Chemical Analysis',
      locator: 'Ch. 22, extraction problems',
      temperatureC: 25,
      medium: 'CHCl₃/H₂O, I → 0',
      basis: 'concentration',
      quality: 'secondary',
      verifiedOn: '2026-07-28',
    },
  },
  {
    id: 'salicilico',
    label: 'Ácido salicílico',
    formula: 'HOC₆H₄COOH',
    type: 'acid',
    logKd: 2.40,
    pKas: [3.00, 13.40],
    neutralIdx: 0,
    system: 'CHCl₃/H₂O',
    source: {
      citation: 'Harris, Quantitative Chemical Analysis',
      locator: 'Ch. 22',
      temperatureC: 25,
      medium: 'CHCl₃/H₂O, I → 0',
      basis: 'concentration',
      quality: 'secondary',
      verifiedOn: '2026-07-28',
    },
  },
  {
    id: 'aspirina',
    label: 'Ácido acetilsalicílico',
    formula: 'HC₉H₇O₄',
    type: 'acid',
    logKd: 1.70,
    pKas: [3.50],
    neutralIdx: 0,
    system: 'CHCl₃/H₂O',
    source: {
      citation: 'Harris, Quantitative Chemical Analysis',
      locator: 'Ch. 22',
      temperatureC: 25,
      medium: 'CHCl₃/H₂O, I → 0',
      basis: 'concentration',
      quality: 'secondary',
      verifiedOn: '2026-07-28',
    },
  },
  {
    id: 'acetico',
    label: 'Ácido acético',
    formula: 'CH₃COOH',
    type: 'acid',
    logKd: -0.23,
    pKas: [4.76],
    neutralIdx: 0,
    system: 'Et₂O/H₂O',
    source: {
      citation: 'Harris, Quantitative Chemical Analysis',
      locator: 'Ch. 22',
      temperatureC: 25,
      medium: 'Et₂O/H₂O, I → 0',
      basis: 'concentration',
      quality: 'secondary',
      verifiedOn: '2026-07-28',
    },
  },
  {
    id: '8hq',
    label: '8-Hidroxiquinolina',
    formula: 'HQ',
    type: 'acid',
    logKd: 2.70,
    pKas: [5.13, 9.89],
    neutralIdx: 1,
    system: 'CHCl₃/H₂O',
    source: {
      citation: 'Skoog, Principles of Analytical Chemistry',
      locator: 'Solvent extraction section',
      temperatureC: 25,
      medium: 'CHCl₃/H₂O, I → 0',
      basis: 'concentration',
      quality: 'secondary',
      verifiedOn: '2026-07-28',
    },
  },
  {
    id: 'dithizone',
    label: 'Ditizona',
    formula: 'H₂Dz',
    type: 'acid',
    logKd: 4.04,
    pKas: [4.52],
    neutralIdx: 0,
    system: 'CHCl₃/H₂O',
    source: {
      citation: 'Harris, Quantitative Chemical Analysis',
      locator: 'Problems 22-13/22-14',
      temperatureC: 25,
      medium: 'CHCl₃/H₂O, I → 0',
      basis: 'concentration',
      quality: 'secondary',
      verifiedOn: '2026-07-28',
    },
  },
  {
    id: 'I2',
    label: 'Yodo molecular',
    formula: 'I₂',
    type: 'acid',
    logKd: 2.83,
    pKas: [],
    neutralIdx: 0,
    system: 'CCl₄/H₂O',
    source: {
      citation: 'Harris, Quantitative Chemical Analysis',
      locator: 'Ch. 22',
      temperatureC: 25,
      medium: 'CCl₄/H₂O, I → 0',
      basis: 'concentration',
      quality: 'secondary',
      verifiedOn: '2026-07-28',
    },
  },
  {
    id: 'cu_8hq',
    label: 'Cu²⁺ + 8-HQ',
    formula: 'Cu(Ox)₂',
    type: 'chelate',
    logKd: 9.10,
    pKas: [],
    neutralIdx: 0,
    n: 2,
    logCHL: -1,
    system: 'CHCl₃/H₂O',
    source: {
      citation: 'Skoog, Principles of Analytical Chemistry',
      temperatureC: 25,
      medium: 'CHCl₃/H₂O, I → 0',
      basis: 'concentration',
      quality: 'secondary',
      verifiedOn: '2026-07-28',
    },
  },
  {
    id: 'zn_8hq',
    label: 'Zn²⁺ + 8-HQ',
    formula: 'Zn(Ox)₂',
    type: 'chelate',
    logKd: 8.70,
    pKas: [],
    neutralIdx: 0,
    n: 2,
    logCHL: -1,
    system: 'CHCl₃/H₂O',
    source: {
      citation: 'Skoog, Principles of Analytical Chemistry',
      temperatureC: 25,
      medium: 'CHCl₃/H₂O, I → 0',
      basis: 'concentration',
      quality: 'secondary',
      verifiedOn: '2026-07-28',
    },
  },
  {
    id: 'fe_8hq',
    label: 'Fe³⁺ + 8-HQ',
    formula: 'Fe(Ox)₃',
    type: 'chelate',
    logKd: 12.10,
    pKas: [],
    neutralIdx: 0,
    n: 3,
    logCHL: -1,
    system: 'CHCl₃/H₂O',
    source: {
      citation: 'Skoog, Principles of Analytical Chemistry',
      temperatureC: 25,
      medium: 'CHCl₃/H₂O, I → 0',
      basis: 'concentration',
      quality: 'secondary',
      verifiedOn: '2026-07-28',
    },
  },
  {
    id: 'pb_dithiz',
    label: 'Pb²⁺ + Ditizona',
    formula: 'Pb(HDz)₂',
    type: 'chelate',
    logKd: 6.30,
    pKas: [],
    neutralIdx: 0,
    n: 2,
    logCHL: -2,
    system: 'CHCl₃/H₂O',
    source: {
      citation: 'Illustrative classroom preset',
      temperatureC: 25,
      medium: 'CHCl₃/H₂O, I → 0',
      basis: 'concentration',
      quality: 'illustrative',
      verifiedOn: '2026-07-28',
      uncertainty: 'Not cross-checked against a primary source',
    },
  },
];
